shellEmulator: true

packages:
  - 'talks/*'

onlyBuiltDependencies:
  - esbuild
  - playwright-chromium

allowBuilds:
  esbuild: true
  playwright-chromium: true

minimumReleaseAgeExclude:
  - '@slidev/cli@52.17.0'
  - '@slidev/client@52.17.0'
  - '@slidev/parser@52.17.0'
  - '@slidev/types@52.17.0'
